name: Compilar Proyecto Eliuth APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: ''

      - name: Instalar SDK necesario
        run: |
          sdkmanager --install "platform-tools"
          sdkmanager --install "platforms;android-35"
          sdkmanager --install "build-tools;35.0.0"

      - name: Aceptar licencias
        run: yes | sdkmanager --licenses || true

      - name: Extraer proyecto
        run: |
          mkdir proyecto
          unzip -q Proyecto_Eliuth_ANDROID_MOVIL.zip -d proyecto

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          gradle-version: '8.7'

      - name: Compilar APK
        working-directory: proyecto/MiNegocio_Android
        run: gradle assembleDebug --no-daemon

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Proyecto-Eliuth-debug-apk
          path: proyecto/MiNegocio_Android/app/build/outputs/apk/debug/app-debug.apk
